### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by moodledan** [aurelia/ux#30]
**I'm submitting a bug report**

* **Library Version:**
aurelia-ux 0.1.14

**Please tell us about your environment:**
* **Operating System:**
OSX 10.11.5

* **Node Version:**
7.2.1

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.48

* **Browser:**
N/A

* **Language:**
TypeScript 2.1.4 

**Current behavior:**
When running `npm run build` the following error is thrown, `npm install` and `jspm install` were run before attempting to run the build.

`$ npm run build`

```
> aurelia-ux@0.1.14 prebuild /Users/dan/Documents/spikes/aurelia-ux/ux-master
> cross-env rimraf dist

```

```
> aurelia-ux@0.1.14 build /Users/dan/Documents/spikes/aurelia-ux/ux-master
> concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"
```

```
[0] 
[0] > aurelia-ux@0.1.14 prebuild:amd /Users/dan/Documents/spikes/aurelia-ux/ux-master
[0] > cross-env rimraf dist/amd
[0] 
```
```
[1] 
[1] > aurelia-ux@0.1.14 prebuild:commonjs /Users/dan/Documents/spikes/aurelia-ux/ux-master
[1] > cross-env rimraf dist/commonjs
[1] 
```
```
[2] 
[2] > aurelia-ux@0.1.14 prebuild:es2015 /Users/dan/Documents/spikes/aurelia-ux/ux-master
[2] > cross-env rimraf dist/es2015
[2] 
```
```
[3] 
[3] > aurelia-ux@0.1.14 prebuild:system /Users/dan/Documents/spikes/aurelia-ux/ux-master
[3] > cross-env rimraf dist/system
[3] 
```
```
[0] 
[0] > aurelia-ux@0.1.14 build:amd /Users/dan/Documents/spikes/aurelia-ux/ux-master
[0] > cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd
[0] 
```
```
[1] 
[1] > aurelia-ux@0.1.14 build:commonjs /Users/dan/Documents/spikes/aurelia-ux/ux-master
[1] > cross-env tsc --project tsconfig.build.json --outDir dist/commonjs --module commonjs
[1] 
```
```
[2] 
[2] > aurelia-ux@0.1.14 build:es2015 /Users/dan/Documents/spikes/aurelia-ux/ux-master
[2] > cross-env tsc --project tsconfig.build.json --outDir dist/es2015 --module es2015
[2] 
```
```
[3] 
[3] > aurelia-ux@0.1.14 build:system /Users/dan/Documents/spikes/aurelia-ux/ux-master
[3] > cross-env tsc --project tsconfig.build.json --outDir dist/system --module system
[3] 
```
```
[0] src/effects/paper-wave.ts(342,5): error TS2531: Object is possibly 'null'.
[0] src/styles/style-controller.ts(60,5): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
[0]   Type 'null' is not assignable to type 'Node'.
[0] src/styles/style-resource.ts(34,12): error TS2322: Type 'Promise<StyleFactory>' is not assignable to type 'Promise<StyleResource>'.
[0]   Type 'StyleFactory' is not assignable to type 'StyleResource'.
[0]     Property 'styleObjectType' is private in type 'StyleFactory' but not in type 'StyleResource'.
```
```
[3] src/effects/paper-wave.ts(342,5): error TS2531: Object is possibly 'null'.
[3] src/styles/style-controller.ts(60,5): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
[3]   Type 'null' is not assignable to type 'Node'.
[3] src/styles/style-resource.ts(34,12): error TS2322: Type 'Promise<StyleFactory>' is not assignable to type 'Promise<StyleResource>'.
[3]   Type 'StyleFactory' is not assignable to type 'StyleResource'.
[3]     Property 'styleObjectType' is private in type 'StyleFactory' but not in type 'StyleResource'.
```
```
[0] 
[3] 
[0] npm
[0]  ERR! Darwin 15.5.0
[0] npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:amd"
[0] npm ERR! node v7.2.1
[0] npm ERR! npm  v3.10.10
[0] npm ERR! 
[0] code ELIFECYCLE
[0] npm ERR! aurelia-ux@0.1.14 build:amd: `cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd`
[0] npm ERR! Exit status 2
[0] npm ERR! 
[0] npm ERR! Failed at the aurelia-ux@0.1.14 build:amd script 'cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the aurelia-ux package,
[0] npm ERR! not with npm itself.
[0] npm ERR!
[0]  Tell the author that this fails on your system:
[0] npm ERR!     cross-env tsc --project tsconfig.build.json --outDir dist/amd --module amd
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs aurelia-ux
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls aurelia-ux
[0] npm ERR! There is likely additional logging output above.
```

**Expected/desired behavior:**
Expected all tests to pass and build to succeed.

**Comment by verbedr** [comment]
I have noticed this too ... there are 3 small typescript errors. After you fix this these, the build still fails on the creation of the documentation. So I have updated the build script and fixed some configuration. And it now builds on my version.

Although I'm not sure about the result. All my dist files are changed so I assume something more fundamental has changed (e.g. typescript .... I'm using the same version as @moodledan).  

What's the best approach to validate my changes or share the updates with you (this is new for me). I just added the changed files to this post but I'm aware this is not how it should be handled ...

[ux.zip](https://github.com/aurelia/ux/files/692449/ux.zip)

**Comment by verbedr** [comment]
Forget about the zip file check pull request #31

**Comment by ZHollingshead** [comment]
Has there been any progress on this? I have the same issue everytime I pull down a fresh branch but the fixes in #31 resolve those issues.

**Comment by verbedr** [comment]
I didn't got any feedback. The PR contains mostly small fixes, I only had to reconfigure typescript to accept the Any keyword. Think this is a new option within the typescript compiler but I'm not sure what the current position is within the aurelia community.

**Comment by verbedr** [comment]
Perhaps we need to ask @EisenbergEffect to poke @jdanyow again?

**Comment by ZHollingshead** [comment]
I am able to get the builds to work without the changes to the `tsconfig.json` file if that is of any help. I am not sure if anything changed that would effect this since you submitted the PR, or if it is an environment thing.

**Comment by moodledan** [comment]
I'm still getting errors when trying to build, I checked out a fresh copy of Master a few moments ago, same errors as previously reported [https://github.com/aurelia/ux/issues/30#issue-198820069](https://github.com/aurelia/ux/issues/30#issue-198820069)

```
[3] src/effects/paper-wave.ts(342,5): error TS2531: Object is possibly 'null'.
[3] src/styles/style-controller.ts(60,5): error TS2322: Type 'Node | null' is not assignable to type 'Node'.
[3]   Type 'null' is not assignable to type 'Node'.
[3] src/styles/style-resource.ts(34,5): error TS2322: Type 'Promise<StyleFactory>' is not assignable to type 'Promise<StyleResource>'.
[3]   Type 'StyleFactory' is not assignable to type 'StyleResource'.
[3]     Property 'styleObjectType' is private in type 'StyleFactory' but not in type 'StyleResource'.
```
Following is from npm-debug.log 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.1.1
3 info using node@v7.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle aurelia-ux@0.1.15~prebuild: aurelia-ux@0.1.15
6 verbose lifecycle aurelia-ux@0.1.15~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle aurelia-ux@0.1.15~prebuild: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/account/git/ux-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
8 verbose lifecycle aurelia-ux@0.1.15~prebuild: CWD: /Users/account/git/ux-master
9 silly lifecycle aurelia-ux@0.1.15~prebuild: Args: [ '-c', 'cross-env rimraf dist' ]
10 silly lifecycle aurelia-ux@0.1.15~prebuild: Returned: code: 0  signal: null
11 info lifecycle aurelia-ux@0.1.15~build: aurelia-ux@0.1.15
12 verbose lifecycle aurelia-ux@0.1.15~build: unsafe-perm in lifecycle true
13 verbose lifecycle aurelia-ux@0.1.15~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/account/git/ux-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
14 verbose lifecycle aurelia-ux@0.1.15~build: CWD: /Users/account/git/ux-master
15 silly lifecycle aurelia-ux@0.1.15~build: Args: [ '-c',
15 silly lifecycle   'concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"' ]
16 silly lifecycle aurelia-ux@0.1.15~build: Returned: code: 1  signal: null
17 info lifecycle aurelia-ux@0.1.15~build: Failed to exec build script
18 verbose stack Error: aurelia-ux@0.1.15 build: `concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:885:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid aurelia-ux@0.1.15
20 verbose cwd /Users/account/git/ux-master
21 error Darwin 15.5.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
23 error node v7.2.1
24 error npm  v4.1.1
25 error code ELIFECYCLE
26 error aurelia-ux@0.1.15 build: `concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"`
26 error Exit status 1
27 error Failed at the aurelia-ux@0.1.15 build script 'concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the aurelia-ux package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     concurrently "npm run build:amd" "npm run build:commonjs" "npm run build:es2015" "npm run build:system"
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs aurelia-ux
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls aurelia-ux
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by ZHollingshead** [comment]
Right, those are Typescript errors. Pull Request #31 fixes those errors but it has not been pulled into the master yet pending a discussion.

**Comment by moodledan** [comment]
Thanks @ZHollingshead

**Comment by verbedr** [comment]
It took me some time but I figured it out. I was using TS 2.1.4 which had this bug in it https://github.com/Microsoft/TypeScript/issues/12822. After upgrading to TS 2.1.6 I could build without problems. I have pushed that change into the PR.
